// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetProjectFiles():Promise<Record<string, any>>;

export function LoadProject(arg1:string):Promise<Record<string, any>>;

export function RunDubbingPipeline(arg1:main.PipelineConfig):Promise<string>;

export function SaveProject(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SynthesizeVoice(arg1:main.VoiceRequest):Promise<Array<number>>;
