// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProjectFiles() {
  return window['go']['main']['App']['GetProjectFiles']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function RunDubbingPipeline(arg1) {
  return window['go']['main']['App']['RunDubbingPipeline'](arg1);
}

export function SaveProject(arg1, arg2) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2);
}

export function SynthesizeVoice(arg1) {
  return window['go']['main']['App']['SynthesizeVoice'](arg1);
}
