// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyLinkedFilesToProject(arg1) {
  return window['go']['main']['App']['CopyLinkedFilesToProject'](arg1);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetDefaultProjectsPath() {
  return window['go']['main']['App']['GetDefaultProjectsPath']();
}

export function GetProjectFiles() {
  return window['go']['main']['App']['GetProjectFiles']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function RunDubbingPipeline(arg1) {
  return window['go']['main']['App']['RunDubbingPipeline'](arg1);
}

export function RunFullPipeline(arg1) {
  return window['go']['main']['App']['RunFullPipeline'](arg1);
}

export function RunPipelineStep(arg1, arg2) {
  return window['go']['main']['App']['RunPipelineStep'](arg1, arg2);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveProject(arg1, arg2) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2);
}

export function ShowProjectInFolder(arg1) {
  return window['go']['main']['App']['ShowProjectInFolder'](arg1);
}

export function SynthesizeVoice(arg1) {
  return window['go']['main']['App']['SynthesizeVoice'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
