// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyLinkedFilesToProject(arg1:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ProjectConfig>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetAppSettings():Promise<main.AppSettings>;

export function GetDefaultProjectsPath():Promise<string>;

export function GetProjectFiles():Promise<Record<string, any>>;

export function GetRecentProjects():Promise<Array<main.ProjectConfig>>;

export function LoadProject(arg1:string):Promise<main.ProjectConfig>;

export function RunDubbingPipeline(arg1:main.PipelineConfig):Promise<string>;

export function RunFullPipeline(arg1:string):Promise<Record<string, any>>;

export function RunPipelineStep(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SaveAppSettings(arg1:main.AppSettings):Promise<void>;

export function SaveProject(arg1:string,arg2:Record<string, any>):Promise<void>;

export function ShowProjectInFolder(arg1:string):Promise<void>;

export function SynthesizeVoice(arg1:main.VoiceRequest):Promise<Array<number>>;

export function UpdateProject(arg1:main.ProjectConfig):Promise<void>;
